- name: Check if OS is RHEL 7, RHEL 8, or RHEL 9
  block:
    - name: Set OS version fact
      set_fact:
        os_version: "{{ ansible_distribution_major_version | int }}"

    - name: Fail if not RHEL 7, 8, or 9
      fail:
        msg: "This playbook only supports RHEL 7, RHEL 8, and RHEL 9"
      when: ansible_distribution != 'RedHat' and os_version not in [7, 8, 9]

- name: Create directories for nessus agent
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - /apps/tools/nessus_agent
    - /opt/nessus_agent

- name: Add bind mount to /etc/fstab
  ansible.builtin.lineinfile:
    path: /etc/fstab
    line: "/apps/tools/nessus_agent /opt/nessus_agent none defaults,bind 0 0"
    state: present

- name: Mount the bind mount
  ansible.builtin.mount:
    src: /apps/tools/nessus_agent
    path: /opt/nessus_agent
    fstype: none
    opts: defaults,bind
    state: mounted

- name: Copy Nessus Agent RPM to /tmp with owner and group set to rothman
  ansible.builtin.copy:
    src: "tenable/files/NessusAgent-10.5.1-el{{ os_version }}.x86_64.rpm"
    dest: "/tmp/NessusAgent-10.5.1-el{{ os_version }}.x86_64.rpm"
    owner: rothman
    group: rothman
    mode: '0755'
    backup: no

- name: Install Nessus Agent RPM from /tmp
  ansible.builtin.yum:
    name: "/tmp/NessusAgent-10.5.1-el{{ os_version }}.x86_64.rpm"
    state: present

- name: Start Nessus Agent service
  ansible.builtin.service:
    name: nessusagent
    state: started

- name: Check Nessus Agent status
  ansible.builtin.shell: /opt/nessus_agent/sbin/nessuscli agent status
  register: agent_status

- name: Display Nessus Agent status
  ansible.builtin.debug:
    var: agent_status.stdout_lines

