---
- name: Check if OS is RHEL 7, RHEL 8, or RHEL 9
  block:
    - name: Set OS version fact
      set_fact:
        os_version: "{{ ansible_distribution_major_version | int }}"

    - name: Fail if not RHEL 7, 8, or 9
      fail:
        msg: "This playbook only supports RHEL 7, RHEL 8, and RHEL 9"
      when: ansible_distribution != 'RedHat' or os_version not in [7, 8, 9]

- name: Check if Nessus Agent is installed
  shell: rpm -q NessusAgent
  register: nessus_installed
  ignore_errors: yes

- name: Display message if Nessus Agent is already installed
  debug:
    msg: "Nessus Agent is already installed on {{ inventory_hostname }}"
  when: nessus_installed.rc == 0

- block:
    - name: Copy Nessus Agent RPM to /tmp/tenable
      copy:
        src: "files/NessusAgent-10.5.1-el{{ os_version }}.x86_64.rpm"
        dest: "/tmp/NessusAgent-10.5.1-el{{ os_version }}.x86_64.rpm"
        mode: '0755'

    - name: Install Nessus Agent RPM
      yum:
        name: "/tmp/NessusAgent-10.5.1-el{{ os_version }}.x86_64.rpm"
        state: present

    - name: Remove Nessus Agent RPM from /tmp after installation
      file:
        path: "/tmp/NessusAgent-10.5.1-el{{ os_version }}.x86_64.rpm"
        state: absent

  when: nessus_installed.rc != 0

- name: Start and enable Nessus Agent service
  systemd:
    name: nessusagent
    enabled: yes
    state: started

